# Using the base theme provided by Github
theme: jekyll-theme-slate

lang: eng
author: Michael Tobin
title: Michael's homepage
description: A site created for BDA 594

# SDSU emblem
favicon: "/img/favicon.ico"

